force-app/main/default/objects/Personnel__c/Personnel__c.object-meta.xml
<CustomObject>
    <label>Personnel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personnel__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <label>Resource Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkOrderTriggerHandler.cls
public without sharing class WorkOrderTriggerHandler {
    public static void assignPersonnel(List<WorkOrder> woList){
        Personnel__c pers = [Select ID from Personnel__c where Resource_Type__c != 'Doctor' ORDER BY Name limit 1];
        for(WorkOrder c: woList){
            c.Personnel__c = pers.ID;
        }
    }
    public static void completeCase(List<WorkOrder> woList){
        List<case> csList = new List<case>();
        Case cs;
        for(WorkOrder wo: woList){
            cs = [Select id, status from Case where Id=:wo.CaseId limit 1];
            cs.status = 'Completed';
            csList.add(cs);
        }
        if(!csList.isEmpty()){
            update csList;
        }
    }
    
}